install.packages("tidyverse")
install.packages("cowplot")
install.packages("MESS")
install.packages("pracma")
install.packages("lsr")
install.packages("BayesFactor")
install.packages("pwr")
install.packages("reticulate")
install.packages("gsubfn")
install.packages("lmerTest")
install.packages("gridExtra")
install.packages("scales")
install.packages("bookdown")
# install.packages("remotes")
devtools::install_github("crsh/papaja")
